services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"  # Puerto de la interfaz web y transmisión sin HTTPS
      - "8920:8920"  # Puerto para la interfaz HTTPS (opcional)
    volumes:
      - /"path de guardado"/jelly/config:/config  # Configuración de Jellyfin
      - /"path de guardado"/jelly/cache:/cache    # Cache de Jellyfin
      - /"path de multimedia":/media    # Carpeta con tus archivos multimedia
    environment:
      - TZ=Europe/Madrid  # Configura la zona horaria según tu ubicación
    devices:
      - /dev/dri:/dev/dri  # Para la aceleración por hardware (opcional)

volumes:
  jellyfin-config:
  jellyfin-cache:
   
