services:
  erugo:
    image: wardy784/erugo:latest
    ports:
      - "9199:9199"  # The web interface will be available at http://localhost:9199
    volumes:
      - erugo-storage:/app/storage  # Persistent storage for shared files
      - erugo-private:/app/private  # Persistent storage for private files (e.g., logo)
    environment:
      - ERUGO_BASE_STORAGE_PATH=/app/storage
      - ERUGO_APP_URL=http://localhost:9199
      - ERUGO_BIND_PORT=9199
      - ERUGO_DATABASE_FILE_PATH=/app/private/erugo.db
      - ERUGO_MAX_SHARE_SIZE=2G
      - ERUGO_JWT_SECRET=change_this_to_a_secure_secret_in_production
      - ERUGO_PRIVATE_DATA_PATH=/app/private
    restart: unless-stopped  # Automatically restart the container

volumes:
  erugo-storage:  # Stores uploaded files
  erugo-private:  # Stores private files including the .db and logo.png