services:
  airsonic:
    image: lscr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      
    volumes:
      - /"path de guardado"/airsonic/config:/config
      - /"path de guardado"/music:/music
      - /"path de guardado"/musica/playlists:/playlists
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
