services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "89:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'daniel123'
    volumes:
      - ' /"path de guardado"/pihole/etc-pihole:/etc/pihole'
      - ' /"path de guardado"/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
