services:
  twingate-celadon-swan:
    image: twingate/connector:1
    container_name: twingate-celadon-swan
    network_mode: "host"
    restart: unless-stopped
    pull_policy: always
    environment:
      TWINGATE_NETWORK: "Nombre de la red"
      TWINGATE_ACCESS_TOKEN: "TWINGATE_ACCESS_TOKEN"
      TWINGATE_REFRESH_TOKEN: "TWINGATE_REFRESH_TOKEN"
      TWINGATE_DNS: "1.1.1.1"
      TWINGATE_LABEL_HOSTNAME: "$(hostname)"
      TWINGATE_LOG_ANALYTICS: "v2"
      TWINGATE_LABEL_DEPLOYED_BY: "docker"