services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - /"path de guardado"/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /"path de guardado"/yacht/compose:/compose
    environment:
      - PUID=0
      - PGID=0
      - COMPOSE_DIR=/compose
    image: selfhostedpro/yacht
volumes:
  yacht:
